version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8088:80"  
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Password
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress_data:/var/www/html 
    restart: always 

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password 
      MYSQL_DATABASE: wp_db 
      MYSQL_USER: wp_user  
      MYSQL_PASSWORD: Password 
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:  
  wordpress_data: 
